/*
 * i2c1.c
 *
 *  Created on: Jan 28, 2024
 *      Author: ahadz
 */


#include <stdint.h>
#include "stm32f746xx.h"
#include "i2c1.h"

void I2C1_GPIO_CONF(void){
	//GPIOB CLOCK ENABLE
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	//ALTERNATE FUNCTION MODE
	GPIOB->MODER |= GPIO_MODER_MODER8_1 | GPIO_MODER_MODER9_1;
	//OUTPUT SPEED HIGH
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8_1 | GPIO_OSPEEDER_OSPEEDR9_1;
	//PULL UP
	GPIOB->PUPDR |= GPIO_PUPDR_PUPDR8_0 | GPIO_PUPDR_PUPDR9_0;
	//ALTERNATE FUNCTION SELECT (AF4)
	GPIOB->AFR[1] |= (0x4 << 0) | (0x4 << 4);
}

void I2C1_CONF(void){
	//I2C1 CLOCK ENABLE
	RCC->APB1ENR |= RCC_APB1ENR_I2C1EN;

	//PERIPHERAL DISABLE (RESET)
	I2C1->CR1 &= ~(I2C_CR1_PE);

	//APB1 PERIPHERAL CLOCK -> 16 MHZ
	//TIMING REGISTER
	//TIMING PRESCALLER
	I2C1->TIMINGR |= (3 << 28);
	//DATA SETUP TIME (SCLDEL)
	I2C1->TIMINGR |= (0x4 << 20);
	//DATA HOLD TIME (SDADEL)
	I2C1->TIMINGR |= (0x2 << 16);
	//SCL HIGH PERIOD
	I2C1->TIMINGR |= (0xF << 8);
	//SCL LOW PERIOD
	I2C1->TIMINGR |= (0x13 << 0);

	//NOSTRECH BIT CLEARED (STM IN MASTER MODE)
	I2C1->CR1 &= ~(I2C_CR1_NOSTRETCH);

	//SET OWN ADDRESS
	I2C1->OAR1 |= 0x03 << 1;

	//PERIPHERAL ENABLE
	I2C1->CR1 |= I2C_CR1_PE;
}

void I2C1_SELECT_AND_START_WR(uint8_t Address){
	I2C1_SET_ADDR(Address | I2C1_WRITE);
	//I2C1_SET_WRITE();
	I2C1_SET_1_BYTE_TRANSFER();
	I2C1_START();

	I2C1_WAIT_FOR_START();
}

void I2C1_SELECT_AND_START_RD(uint8_t Address){
	I2C1_SET_ADDR(Address | I2C1_READ);
	//I2C1_SET_READ();
	I2C1_SET_1_BYTE_TRANSFER();
	I2C1_SEND_NACK();
	I2C1_START();

	I2C1_WAIT_FOR_START();
}

void I2C1_SEND_BYTE(uint8_t Byte){
	I2C1_WAIT_FOR_TXDR_EMPTY();
	I2C1->TXDR = Byte;
	printf("%d\n", Byte);
	I2C1_WAIT_FOR_TXDR_EMPTY();
}

uint8_t I2C1_READ_BYTE(void){
	I2C1_WAIT_FOR_REC_COMPLETE();
	return I2C1->RXDR;
}
